//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyFlight.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aircraft
    {
        public Aircraft()
        {
            this.Flights = new HashSet<Flight>();
        }
    
        public int ac_id { get; set; }
        public int acm_id { get; set; }
        public string ac_lic_no { get; set; }
        public int airline_id { get; set; }
        public string aircraft_status { get; set; }
    
        public virtual AircraftModel AircraftModel { get; set; }
        public virtual Airline Airline { get; set; }
        public virtual ICollection<Flight> Flights { get; set; }
    }
}
