//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyFlight.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AircraftModel
    {
        public AircraftModel()
        {
            this.Aircrafts = new HashSet<Aircraft>();
        }
    
        public int acm_id { get; set; }
        public string acm_name { get; set; }
        public decimal ac_speed { get; set; }
        public int act_id { get; set; }
        public int ab_id { get; set; }
    
        public virtual AircraftBrand AircraftBrand { get; set; }
        public virtual AircraftType AircraftType { get; set; }
        public virtual ICollection<Aircraft> Aircrafts { get; set; }
    }
}
