//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyFlight.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class AircraftBrand
    {
        public AircraftBrand()
        {
            this.AircraftModels = new HashSet<AircraftModel>();
        }
    
        public int ab_id { get; set; }
        public string ac_name { get; set; }
    
        public virtual ICollection<AircraftModel> AircraftModels { get; set; }
    }
}
