//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyFlight.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airline
    {
        public Airline()
        {
            this.Aircrafts = new HashSet<Aircraft>();
            this.Logins = new HashSet<Login>();
            this.Tickets = new HashSet<Ticket>();
        }
    
        public int airline_id { get; set; }
        public string airline_name { get; set; }
        public string airline_address { get; set; }
        public string airline_phone { get; set; }
        public string airline_regno { get; set; }
        public string airline_status { get; set; }
    
        public virtual ICollection<Aircraft> Aircrafts { get; set; }
        public virtual ICollection<Login> Logins { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
