//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyFlight.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airport
    {
        public Airport()
        {
            this.Distances = new HashSet<Distance>();
            this.Distances1 = new HashSet<Distance>();
            this.Stoppages = new HashSet<Stoppage>();
            this.Stoppages1 = new HashSet<Stoppage>();
        }
    
        public int airport_id { get; set; }
        public string airport1 { get; set; }
        public string accro_name { get; set; }
        public string coordinates { get; set; }
        public string City { get; set; }
    
        public virtual ICollection<Distance> Distances { get; set; }
        public virtual ICollection<Distance> Distances1 { get; set; }
        public virtual ICollection<Stoppage> Stoppages { get; set; }
        public virtual ICollection<Stoppage> Stoppages1 { get; set; }
    }
}
