//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyFlight.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Day
    {
        public Day()
        {
            this.Schedules = new HashSet<Schedule>();
        }
    
        public int day_id { get; set; }
        public string day1 { get; set; }
    
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}
