//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyFlight.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distance
    {
        public Distance()
        {
            this.Stoppages = new HashSet<Stoppage>();
        }
    
        public int distance_id { get; set; }
        public int departure_port_id { get; set; }
        public int arrival_port_id { get; set; }
        public decimal distance1 { get; set; }
    
        public virtual Airport Airport { get; set; }
        public virtual Airport Airport1 { get; set; }
        public virtual ICollection<Stoppage> Stoppages { get; set; }
    }
}
