//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyFlight.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public Flight()
        {
            this.Schedules = new HashSet<Schedule>();
            this.Sections = new HashSet<Section>();
            this.Stoppages = new HashSet<Stoppage>();
            this.Transits = new HashSet<Transit>();
        }
    
        public int flight_id { get; set; }
        public int ac_id { get; set; }
        public string flight_status { get; set; }
    
        public virtual Aircraft Aircraft { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
        public virtual ICollection<Stoppage> Stoppages { get; set; }
        public virtual ICollection<Transit> Transits { get; set; }
    }
}
