//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyFlight.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int login_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string user_type { get; set; }
        public Nullable<int> customer_id { get; set; }
        public string recovery_phone { get; set; }
        public string email { get; set; }
        public Nullable<int> airline_id { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
