//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyFlight.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int pay_id { get; set; }
        public int ticket_id { get; set; }
        public decimal total_fair { get; set; }
        public decimal paid { get; set; }
        public decimal balance { get; set; }
        public string account_no { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
