//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyFlight.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PricePool
    {
        public int price_poll_id { get; set; }
        public decimal PerKM_Price { get; set; }
        public int section_id { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
