//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyFlight.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int sh_id { get; set; }
        public int day_id { get; set; }
        public int flight_id { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
