//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyFlight.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.PricePools = new HashSet<PricePool>();
        }
    
        public int section_id { get; set; }
        public int class_id { get; set; }
        public int total_seat { get; set; }
        public int flight_id { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual ICollection<PricePool> PricePools { get; set; }
    }
}
