//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyFlight.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stoppage
    {
        public int stoppage_id { get; set; }
        public int flight_id { get; set; }
        public int departure_port_id { get; set; }
        public int arrival_port_id { get; set; }
        public System.TimeSpan departure_time { get; set; }
        public System.TimeSpan arrival_time { get; set; }
        public int distance_id { get; set; }
    
        public virtual Airport Airport { get; set; }
        public virtual Airport Airport1 { get; set; }
        public virtual Distance Distance { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
