//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookMyFlight.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.CancelRequests = new HashSet<CancelRequest>();
            this.Payments = new HashSet<Payment>();
            this.Seats = new HashSet<Seat>();
            this.Transits = new HashSet<Transit>();
        }
    
        public int ticket_id { get; set; }
        public System.DateTime book_date { get; set; }
        public System.DateTime flight_date { get; set; }
        public int customer_id { get; set; }
        public Nullable<decimal> total_fair { get; set; }
        public string status { get; set; }
        public int airline_id { get; set; }
    
        public virtual Airline Airline { get; set; }
        public virtual ICollection<CancelRequest> CancelRequests { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<Seat> Seats { get; set; }
        public virtual ICollection<Transit> Transits { get; set; }
    }
}
