//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Logins = new HashSet<Login>();
            this.Newses = new HashSet<News>();
            this.Opinions = new HashSet<Opinion>();
        }
    
        public int UserId { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Occupation { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    
        public virtual ICollection<Login> Logins { get; set; }
        public virtual ICollection<News> Newses { get; set; }
        public virtual ICollection<Opinion> Opinions { get; set; }
    }
}
